### PR TITLE
add some fields to grab the info need to push the Docker image to a registry

### PR DESCRIPTION
**Pull request by kuisathaverat**
* customSettings field to store (or whatever you want)
  * A boolean field to enable push
  * A String field to store the registry URL (http://docker.io)
  * A String field to store the credentials Id on Jenkins

@oleg-nenashev

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Is there any reference implementation for these fields?

**Comment by kuisathaverat** [comment]
In order to be able to push the docker image generated by CWP to a private Docker registry, could be nice to have the data on the YAML, if the field does not exist on beans the CWP launch a serialization error, obviously.

```
Exception in thread "main" com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "push" (class io.jenkins.tools.warpackager.lib.config.DockerBuildSettings), not marked as ignorable (4 known properties: "base", "tag", "outputDir", "build"])
 at [Source: java.io.FileInputStream@3b084709; line: 13, column: 15] (through reference chain: io.jenkins.tools.warpackager.lib.config.Config["buildSettings"]->io.jenkins.tools.warpackager.lib.config.BuildSettings["docker"]->io.jenkins.tools.warpackager.lib.config.DockerBuildSettings["push"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:111)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2924)
	at io.jenkins.tools.warpackager.lib.config.Config.load(Config.java:71)
	at io.jenkins.tools.warpackager.lib.config.Config.loadConfig(Config.java:100)
	at io.jenkins.tools.warpackager.cli.Main.main(Main.java:40)
```

thus, I make this PR to add the needed fields to push a Docker image to a private registry in a pipeline that uses the CWP, something like this

```
    def pushDockerImage = metadata.packaging?.config?.buildSettings?.docker?.push
    def dockerRegistry = metadata.packaging?.config?.buildSettings?.docker?.registryURL
    def dockerRegistryCredentialsId = metadata.packaging?.config?.buildSettings?.docker?.credentialsId
    def dockerTag = metadata?.packaging?.config?.buildSettings?.docker.tag
    
    if(pushDockerImage && dockerRegistry != null 
      && dockerRegistryCredentialsId != null && dockerTag != null){
      docker.withRegistry(dockerRegistry, dockerRegistryCredentialsId) {
          docker.image(dockerTag).push()
      }
    }
```

**Comment by oleg-nenashev** [comment]
Ack, let me think about it. We will need to document it so that it does not confuse users.
They may expect push/registryUrl to be happening inside Custom WAR Packager, and it is a reasonable expectation. If we could somehow pass credentials to CWP (e.g. by referencing file or environment variables), I could implement the push logic in CWP

**Comment by kuisathaverat** [comment]
other option it is to allow an open String field like customSettings, it would be used for custom proposes like this one, in my case I could put a JSON with the push settings

```
    buildSettings:
      version: 2.121.1
      docker:
        base: "jenkins/jenkins:2.121.1"
        tag: "jenkins/artifact-manager-s3"
        build: true
        customSettings: "{push: true, registryURL: http://my-docker.exemple.com, credentialsId: my-credentials}"
```

**Comment by oleg-nenashev** [comment]
@kuisathaverat Yes, it would work for me

**Comment by kuisathaverat** [comment]
@oleg-nenashev I replaced the field with only one custom field.

**Pull request merged**
