### PR TITLE
Add a download link for the cwp binary file

### PR DESCRIPTION
**Pull request by LinuxSuRen**

### CODE REVIEW

**Comment by LinuxSuRen** [comment]
> Needs justification. I would also argue it should be in the Jenkins registry, not in jenkins-zh

Sorry about that. That's a typo.

**Comment by LinuxSuRen** [comment]
I would suggest we deploy custom-war-packager-cli.jar to GitHub release or [bintray](https://bintray.com/).

**Comment by LinuxSuRen** [comment]
I found out the release binray files already exists in https://repo.jenkins-ci.org/. I guess this PR can be closed.

**Comment by oleg-nenashev** [comment]
You can document it in README tho

**Comment by LinuxSuRen** [comment]
Sure. I'll do it later.

**Pull request merged**
