### PR TITLE
Add support of Jenkinsfile Runner docker image packaging

### PR DESCRIPTION
**Pull request by oleg-nenashev**
Just a hackish prototype I assembled on the weekend. It allows to package arbitrary plugins, JCasC settings and groovy scripts... using a single YAML definition. Both utility packaging and Docker image build are supported

Demo: https://github.com/oleg-nenashev/custom-war-packager/tree/jenkinsfileRunnerDemo/demo/jenkinsfile-runner 

```
docker run --rm -v $PWD/Jenkinsfile:/workspace/Jenkinsfile jenkins-experimental/cwp-jenkinsfile-runner-demo
```

```yaml
bundle:
  groupId: "io.jenkins.tools.custom-war-packager.demo"
  artifactId: "jenkinsfile-runner"
  vendor: "Jenkins project"
  title: "Jenkinsfile Runner demo"
  description: "Jenkinsfile Runner Docker Image, produced by Custom WAR Packager"
buildSettings:
  jenkinsfileRunner:
    source:
      groupId: "io.jenkins"
      artifactId: "jenkinsfile-runner"
      build:
        # Jenkinsfile Runner produces appassembler directory which is not a maven artifact
        #TODO: replace once Jenkinsfile Runner archives runner to ZIP & CWP is updated
        noCache: true
      source:
        git: https://github.com/kohsuke/jenkinsfile-runner.git
        commit: 8ff9b1e9a097e629c5fbffca9a3d69750097ecc4
    docker:
      base: "jenkins/jenkins:2.121.3"
      tag: "jenkins-experimental/cwp-jenkinsfile-runner-demo"
      build: true
war:
  groupId: "org.jenkins-ci.main"
  artifactId: "jenkins-war"
  source:
    version: "2.121.3"
plugins:
  - groupId: "org.jenkins-ci.plugins.workflow"
    artifactId: "workflow-job"
    source:
      version: "2.24"
  - groupId: "org.jenkins-ci.plugins"
    artifactId: "pipeline-utility-steps"
    source:
      version: "2.1.0"
  # ... and so on
  - groupId: "io.jenkins"
    artifactId: "configuration-as-code"
    source:
      version: "1.0-rc2"
systemProperties: {
    jenkins.model.Jenkins.slaveAgentPort: "50000",
    jenkins.model.Jenkins.slaveAgentPortEnforce: "true"}
casc:
  - id: "jcasc"
    source:
      dir: casc.yml
groovyHooks:
  - type: "init"
    id: "initScripts"
    source:
      dir: init.groovy
```

It works, but some testing is required before it gets merged (esp. JCasC-driven configuration). There is also a number of performance tweaks which could be applied in Jenkinsfile Runner to speed up the initialization and execution

## Changelog:

- [x] - Add support of disabling artifact cache for dependencies (`build.noCache` flag)
- [x] - Add support of building Jenkinsfile Runner binaries and Docker images

CC @jstrachan @rawlingsj @rajdavies @ndeloof

### CODE REVIEW

**Comment by raul-arabaolaza** [comment]
So useful, thanks for this @oleg-nenashev

**Comment by oleg-nenashev** [comment]
Let me keep it open for a while, there are some follow-up patches

**Comment by ndeloof** [comment]
Afaict this is for kk's Jenkinsfile-runner, which is not the same as mine deployed as Jenkins/Jenkinsfile-runner docker image.

**Comment by oleg-nenashev** [comment]
Will merge it and document as experimental feature for now (until I integrate the upstream Jenkinsfile Runner)

**Pull request merged**
